### PR TITLE
bump bm dep to 0.2

### PR DESCRIPTION
**Pull request by feynmanliang**
### Motivation
Please describe your motivation for the changes. Provide link to any related issues.

### Changes proposed
Outline the proposed changes and alternatives considered.

### Test Plan
Please provide clear instructions on how the changes were verified. Attach screenshots if applicable.

### Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **[CONTRIBUTING](https://github.com/facebookresearch/pplbench/blob/main/CONTRIBUTING.md)** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by horizon-blue** [comment]
Are we planning to use some features that's only available in BM 0.2.0+ in PPL Bench? If not, then it shouldn't hurt to keep supporting older version of BM :). WDYT?

**Comment by feynmanliang** [comment]
We are using NNC on by default in the BM NUTS results in #122

**Comment by horizon-blue** [comment]
> On a related note, many of the other existing PPL version pins (https://pplbench.org/docs/working_with_ppls/) are actually not working at the moment.

That's a good catch. I totally forgot that we're pining the PPL versions there in the documentation. We should update that page to be consistent with what our CI is testing against.

**Comment by feynmanliang** [comment]
> > On a related note, many of the other existing PPL version pins (https://pplbench.org/docs/working_with_ppls/) are actually not working at the moment.
> 
> That's a good catch. I totally forgot that we're pining the PPL versions there in the documentation. We should update that page to be consistent with what our CI is testing against.

[T131563496](https://www.internalfb.com/intern/tasks/?t=131563496)

**Pull request closed without merging**
